openapi: 3.0.0
info:
  title: Weather information api
  description: Weather information api from openweathermap.org
  contact:  
    name: Nitin Saxena
    email: nitinsaxena1710@gmail.com
  version: 1.0.0
servers: 
  - url: http://localhost:8080
paths:  
  /weather:
    description: Weather information  
    get:
      description: operation to fetch weather information of a city
      parameters: 
      - in: query
        name: Name of city
        required: true
        schema:
          type: string 
          example: Bangalore
      responses:
        200:
          description: Success response 
          content:
            application/json:
              schema:
                type: object
                properties:
                  temp:
                    type: string 
                    description: Action when the temperature is high 
                  rain:
                    type: string 
                    description: Action on rain forecast 
                  wind:
                    type: string
                    description: Information on wind
                    
          
           
            
            
            
              
          
        
        
            
      
            
                
            
      
    
    
  
    





  

  
  

  
    
  

  